In [1]:

#train a logistic regression classifier to predict whether flower is iris verginica or not 
from  sklearn import datasets
from sklearn.linear_model import LogisticRegression
import numpy as np
iris=datasets.load_iris()
print(list(iris.keys()))

 

['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module']


In [2]:
print(iris["data"])
print(iris["target"])
print(iris["DESCR"])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
print(iris["data"].shape)

(150, 4)


In [4]:
X=(iris["data"][:,3:])
y=(iris["target"]==2).astype(np.int)
print(y)
clf=LogisticRegression()
clf.fit(X,y)
example=clf.predict(([[2.6]]))
print(example) 



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]
[1]


C:\Users\Dell\AppData\Local\Temp/ipykernel_3284/618605148.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=(iris["target"]==2).astype(np.int)


In [6]:
#use matplotlib
X_new=np.linspace(0,3,1000).reshape(-1,1)
print(X_new)

[[0.        ]
 [0.003003  ]
 [0.00600601]
 [0.00900901]
 [0.01201201]
 [0.01501502]
 [0.01801802]
 [0.02102102]
 [0.02402402]
 [0.02702703]
 [0.03003003]
 [0.03303303]
 [0.03603604]
 [0.03903904]
 [0.04204204]
 [0.04504505]
 [0.04804805]
 [0.05105105]
 [0.05405405]
 [0.05705706]
 [0.06006006]
 [0.06306306]
 [0.06606607]
 [0.06906907]
 [0.07207207]
 [0.07507508]
 [0.07807808]
 [0.08108108]
 [0.08408408]
 [0.08708709]
 [0.09009009]
 [0.09309309]
 [0.0960961 ]
 [0.0990991 ]
 [0.1021021 ]
 [0.10510511]
 [0.10810811]
 [0.11111111]
 [0.11411411]
 [0.11711712]
 [0.12012012]
 [0.12312312]
 [0.12612613]
 [0.12912913]
 [0.13213213]
 [0.13513514]
 [0.13813814]
 [0.14114114]
 [0.14414414]
 [0.14714715]
 [0.15015015]
 [0.15315315]
 [0.15615616]
 [0.15915916]
 [0.16216216]
 [0.16516517]
 [0.16816817]
 [0.17117117]
 [0.17417417]
 [0.17717718]
 [0.18018018]
 [0.18318318]
 [0.18618619]
 [0.18918919]
 [0.19219219]
 [0.1951952 ]
 [0.1981982 ]
 [0.2012012 ]
 [0.2042042 ]
 [0.20720721]
 [0.21021021]
 [0.21

In [ ]:
#train a logistic regression classifier
