In [2]:
import numpy as np
a=[1,2,3,4]
print(a)



[1, 2, 3, 4]


In [26]:
import numpy as np
a[0,1]=45 # to chnage the value at 0


In [22]:
a.dtype #kis type ka hai

dtype('int32')

In [21]:
a+b

array([[ 6,  8],
       [10, 12]])

In [17]:
a-b

array([[-4, -4],
       [-4, -4]])

In [18]:
a*b

array([[ 5, 12],
       [21, 32]])

In [19]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [20]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [6]:
#view vs copy in numpy
#view
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6]
slicing[:]=0
a



array([10, 20, 30,  0,  0,  0, 70, 80])

In [7]:
#important function sin numpy
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #smallest value present at which index
print(np.argmax(arr)) #maximum value present at which index
print(np.sqrt(arr))   #square root calculation
print(np.sin(arr))    #sin value
print(np.cos(arr))    #cos value
print(np.linspace(1,2,5))  # 1 se lker 2 tak 5 values aur 5 values k beech ka dufference same hona chahiye

10
50
0
4
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[1.   1.25 1.5  1.75 2.  ]


In [8]:
#important functions in numpy in 2d
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix
#np.min(matrix)
#np.max(matrix)
#np.sum(matrix)


array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [9]:
#2d array
#np.min(matrix,axis=1) shows min value along row
#np.max(matrix,axis=0) finds col wise max
#np.cumseum(matrix) cummulative sum
import numpy as np
np.sum(matrix,axis=1)
np.cumsum(matrix)


array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [ ]:
#conditional slection in numpy
import numpy as np
arr=np.arange(1,16)
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [11]:
import numpy as np

a[a%2==0] #print those values divisible by 2
a[a>5]=0 #those values greater than 5 will become 0
a



array([0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#important functions in numpy
#np.shuffle(arr)(shuffles the array)
#np.unique(arr)---displays unique values of array
#np.unique(arr).size----counts the unique count of elements



In [12]:
#stacking(vertical and horizontal)
import numpy as numpy
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr1
arr2
np.hstack((arr1,arr2))
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
#copy
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6].copy()
slicing[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [14]:
#seed function in numoy
#seed--use to fix generation of random numbers
import numpy as np
np.random.seed(12)
array=np.random.randint(1,100,10)
array

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [15]:
#various operations in numpy array(1D)
import numpy as np
arr=np.arange(1,5)
arr*2

array([2, 4, 6, 8])

In [16]:
#operations on 2D array
#use a.dot(b) to multiply using rules of matrix
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
import numpy as np
arr=np.arange(1,5)
arr**2 # power nikalo

array([ 1,  4,  9, 16])

In [ ]:
#adding and subtracting two array
import numpy as np
arr1=np.arange(1,5)
arr2=np.arange(5,9)
arr1+arr2

array([ 6,  8, 10, 12])

In [ ]:
arr1-arr2

array([-4, -4, -4, -4])

In [ ]:
import numpy as np
arr=np.arange(1,5)
arr+2

array([3, 4, 5, 6])

In [ ]:
#slicing in 2d array in numpy
import numpy as np
a=np.array[[10,20,30],[40,50,60],[70,80,90]]



TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
#chnage the shape of array(reshaping)
import numpy as np
arr=np.random.randint(1,50,12)
arr=arr.reshape(4,3) #or (3,4)
arr



array([[ 2, 17,  3],
       [20,  9, 45],
       [48, 11, 15],
       [24,  9, 44]])

In [ ]:
#2d to 1d
arr=arr.reshape(12)
arr

array([ 2, 17,  3, 20,  9, 45, 48, 11, 15, 24,  9, 44])

In [ ]:
#eye--this function creates an array with all the diagonal elements as 1 and rest as 0
import numpy as np

arr=np.eye(5)

arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#diag---this function creates a 2d array with all the diagonal elements as the given value and rest as 0(in a square matrix)
import numpy as np
arr=np.diag([2,3,4,5])
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [ ]:
import numpy as np
arr=np.diag([2,3,4,5])
np.diag(arr)

array([2, 3, 4, 5])

In [ ]:
#randint---This function is used to generate a random number between a given range
import numpy as np
arr=np.random.randint(1,10,3)
arr

array([3, 5, 4])

In [ ]:
#rand---this function is used to generate a random value between 0 to 1
import numpy as np
arr=np.random.rand(5,4)
arr


array([[0.10344751, 0.04198975, 0.89061456, 0.3196484 ],
       [0.93920616, 0.84365482, 0.16321966, 0.82863401],
       [0.9335833 , 0.73314801, 0.81119467, 0.26572018],
       [0.72712406, 0.0747738 , 0.28326874, 0.19641994],
       [0.90985807, 0.96455351, 0.54992409, 0.42344293]])

In [ ]:
#randn--used to generate arandom value close to 0.This may return positive or negative number as well
import numpy as np
arr=np.random.randn(5)
arr

array([ 0.13396423, -1.30559905,  0.05546825, -0.61962618,  0.85790396])

In [ ]:
#indexing and slicing in numpy 1-d array
import numpy as np
a=[]
size=int(input("enter the size"))
for i in range(size):
    val=int(input("enter the value"))
    a.append(val)
array=np.array(a)
for i in range(array.size):
    print(array[i])
sum=0
for i in range(array.size):
    sum=sum+array[i]
    print(sum)


2
4
6
8
10
2
6
12
20
30


In [ ]:
#slicing in 1-d
import numpy as np
a=[]
size=int(input("enter the size"))
for i in range(size):
    val=int(input("enter the value"))
    a.append(val)
array=np.array(a)
for i in range(array.size):
    print(array[i])
arr=array[2:4]
print(arr)


2
4
6
8
10
[6 8]


In [ ]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#creating 1-d array 
import numpy as np 
a=[1,2,3,4,5]
myarr=np.array(a)
myarr

array([1, 2, 3, 4, 5])

In [ ]:
#take value form user and convert to array
import numpy as np
a=[]
n=int(input("enter size of array"))
for i in range(n):
    val=int(input("enter number"))
    a.append(val)
myarray=np.array(a)
myarray



array([1, 2, 3, 4, 5])

In [ ]:
#create a 2d array
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarray=np.array(a)
print(myarray)
print(myarray.ndim)  #myarray.ndim--to know dimension
print(myarray.shape) #myarray.shape--to know shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
#numpy functions in python
#1)  zeros--this function creates an array and fill all values with zero
import numpy as np
arr=np.zeros((5,4)) #1d array k liye single bracket aur 2d array k liye tuple
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#ones---fill the array with value 1

import numpy as np
arr=np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])